// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4QLJatOw0THcqm3hMpiip0TBrtl1FkvI',
    appId: '1:34873830307:web:6e3fb5ea1370a473460816',
    messagingSenderId: '34873830307',
    projectId: 'fashion-1e03f',
    authDomain: 'fashion-1e03f.firebaseapp.com',
    storageBucket: 'fashion-1e03f.firebasestorage.app',
    measurementId: 'G-LH3H28XFHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp7DNzo9S4NDuq8-XywDcjlj0w9XhmK8c',
    appId: '1:34873830307:android:a776a68a39939c6b460816',
    messagingSenderId: '34873830307',
    projectId: 'fashion-1e03f',
    storageBucket: 'fashion-1e03f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdRgxyX0fUIShBrNZdvKnAPE_UxXIsOAU',
    appId: '1:34873830307:ios:8c4049fc6a651a2d460816',
    messagingSenderId: '34873830307',
    projectId: 'fashion-1e03f',
    storageBucket: 'fashion-1e03f.firebasestorage.app',
    iosBundleId: 'com.example.fashionStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdRgxyX0fUIShBrNZdvKnAPE_UxXIsOAU',
    appId: '1:34873830307:ios:8c4049fc6a651a2d460816',
    messagingSenderId: '34873830307',
    projectId: 'fashion-1e03f',
    storageBucket: 'fashion-1e03f.firebasestorage.app',
    iosBundleId: 'com.example.fashionStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4QLJatOw0THcqm3hMpiip0TBrtl1FkvI',
    appId: '1:34873830307:web:1847550eaddb4319460816',
    messagingSenderId: '34873830307',
    projectId: 'fashion-1e03f',
    authDomain: 'fashion-1e03f.firebaseapp.com',
    storageBucket: 'fashion-1e03f.firebasestorage.app',
    measurementId: 'G-E0CYNKZKGY',
  );
}
